# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fae0216c3abaf0125ad2a14a05044495614530c9b2c453650ed7e6fbcfcb6d7225e5c35068bb3a4dd476bdb1007bfecc7663616db92f4f39cd20a974d5dbc450

test:
  secret_key_base: fb70c00fa94554fd13f41a6b1b27718fc376c2a195ba1057fac36e7fd0656be9bf9e82bce3fb89f504f28aa8b512577cda76d7f81a6265e896c958d69627e472

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
